--- 
abstract: the adaptor.
author: 
  - Tokuhiro Matsuno <tokuhirom AAJKLFJEF GMAIL COM>
build_requires: 
  Test::More: 0
  YAML: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Sledge-Model-Factory
no_index: 
  directory: 
    - inc
    - t
requires: 
  perl: 5.8.0
version: 0.01
